import type { Recipe } from './types/recipe';

export const mockRecipes: Recipe[] = [
  {
    id: '1',
    title: 'Tarte aux pommes classique',
    description:
      'Une délicieuse tarte aux pommes avec une pâte croustillante et des pommes fondantes.',
    image: '/tarte-aux-pommes-doree.jpg',
    rating: 4.8,
    time: '1h 30min',
    difficulty: 'Moyen',
    tags: ['Dessert', 'Classique', 'Automne'],
    author: 'Marie Dupont',
    ingredients: [
      { name: 'Pâte brisée', quantity: '1' },
      { name: 'Pommes', quantity: '6' },
      { name: 'Sucre', quantity: '100g' },
      { name: 'Beurre', quantity: '50g' },
      { name: 'Cannelle', quantity: '1 c. à café' },
    ],
    steps: [
      'Préchauffer le four à 180°C.',
      'Étaler la pâte dans un moule à tarte.',
      'Éplucher et couper les pommes en tranches.',
      'Disposer les pommes sur la pâte.',
      'Saupoudrer de sucre et de cannelle.',
      'Ajouter des noisettes de beurre.',
      'Enfourner pour 45 minutes.',
    ],
    isPublic: true,
  },
  {
    id: '2',
    title: 'Salade César végétarienne',
    description: 'Une version légère et végétarienne de la célèbre salade César.',
    image: '/salade-cesar-fraiche.jpg',
    rating: 4.5,
    time: '20min',
    difficulty: 'Facile',
    tags: ['Végétarien', 'Rapide', 'Healthy', 'Entrée'],
    author: 'Jean Martin',
    ingredients: [
      { name: 'Laitue romaine', quantity: '1' },
      { name: 'Croûtons', quantity: '100g' },
      { name: 'Parmesan', quantity: '50g' },
      { name: 'Yaourt grec', quantity: '150g' },
      { name: 'Citron', quantity: '1' },
      { name: 'Ail', quantity: '1 gousse' },
    ],
    steps: [
      'Laver et couper la laitue.',
      "Préparer la sauce avec le yaourt, le citron et l'ail.",
      'Mélanger la salade avec la sauce.',
      'Ajouter les croûtons et le parmesan râpé.',
      'Servir immédiatement.',
    ],
    isPublic: true,
  },
  {
    id: '3',
    title: 'Boeuf bourguignon traditionnel',
    description: 'Le grand classique de la cuisine française, mijoté pendant des heures.',
    image: '/boeuf-bourguignon-mijote.jpg',
    rating: 4.9,
    time: '3h',
    difficulty: 'Difficile',
    tags: ['Plat principal', 'Classique', 'Hiver'],
    author: 'Pierre Dubois',
    ingredients: [
      { name: 'Boeuf à braiser', quantity: '1kg' },
      { name: 'Vin rouge', quantity: '750ml' },
      { name: 'Carottes', quantity: '4' },
      { name: 'Oignons', quantity: '3' },
      { name: 'Lardons', quantity: '200g' },
      { name: 'Champignons', quantity: '250g' },
      { name: 'Bouquet garni', quantity: '1' },
    ],
    steps: [
      'Faire mariner le boeuf dans le vin rouge pendant 12h.',
      'Faire revenir les lardons et réserver.',
      'Faire dorer la viande de tous les côtés.',
      'Ajouter les légumes et la marinade.',
      'Laisser mijoter à feu doux pendant 2h30.',
      'Ajouter les champignons 30 minutes avant la fin.',
      'Servir avec des pommes de terre ou des pâtes.',
    ],
    isPublic: true,
  },
  {
    id: '4',
    title: 'Smoothie bowl aux fruits rouges',
    description: 'Un petit-déjeuner sain et coloré pour bien commencer la journée.',
    image: '/smoothie-bowl-fruits-rouges.jpg',
    rating: 4.6,
    time: '10min',
    difficulty: 'Facile',
    tags: ['Healthy', 'Rapide', 'Vegan', 'Dessert'],
    author: 'Sophie Laurent',
    ingredients: [
      { name: 'Bananes congelées', quantity: '2' },
      { name: 'Fruits rouges congelés', quantity: '200g' },
      { name: "Lait d'amande", quantity: '100ml' },
      { name: 'Granola', quantity: '50g' },
      { name: 'Fruits frais', quantity: 'au choix' },
    ],
    steps: [
      'Mixer les bananes et fruits rouges congelés avec le lait.',
      'Verser dans un bol.',
      'Décorer avec le granola et les fruits frais.',
      'Déguster immédiatement.',
    ],
    isPublic: true,
  },
  {
    id: '5',
    title: 'Risotto aux champignons',
    description: 'Un risotto crémeux et parfumé aux champignons de saison.',
    image: '/risotto-champignons-cremeux.jpg',
    rating: 4.7,
    time: '45min',
    difficulty: 'Moyen',
    tags: ['Plat principal', 'Végétarien', 'Italien'],
    author: 'Marco Rossi',
    ingredients: [
      { name: 'Riz arborio', quantity: '300g' },
      { name: 'Champignons', quantity: '400g' },
      { name: 'Bouillon de légumes', quantity: '1L' },
      { name: 'Vin blanc', quantity: '100ml' },
      { name: 'Parmesan', quantity: '80g' },
      { name: 'Oignon', quantity: '1' },
      { name: 'Beurre', quantity: '50g' },
    ],
    steps: [
      "Faire revenir l'oignon émincé dans le beurre.",
      'Ajouter le riz et nacrer pendant 2 minutes.',
      'Déglacer avec le vin blanc.',
      'Ajouter le bouillon louche par louche en remuant.',
      'Faire revenir les champignons à part.',
      'Incorporer les champignons et le parmesan en fin de cuisson.',
      'Servir immédiatement.',
    ],
    isPublic: true,
  },
  {
    id: '6',
    title: 'Cookies au chocolat moelleux',
    description: 'Des cookies américains avec des pépites de chocolat fondantes.',
    image: '/cookies-chocolat-moelleux.jpg',
    rating: 4.9,
    time: '25min',
    difficulty: 'Facile',
    tags: ['Dessert', 'Rapide', 'Goûter'],
    author: 'Emma Wilson',
    ingredients: [
      { name: 'Farine', quantity: '250g' },
      { name: 'Beurre', quantity: '125g' },
      { name: 'Sucre roux', quantity: '150g' },
      { name: 'Oeufs', quantity: '2' },
      { name: 'Pépites de chocolat', quantity: '200g' },
      { name: 'Levure', quantity: '1 c. à café' },
    ],
    steps: [
      'Préchauffer le four à 180°C.',
      'Mélanger le beurre mou et le sucre.',
      'Ajouter les oeufs un par un.',
      'Incorporer la farine et la levure.',
      'Ajouter les pépites de chocolat.',
      'Former des boules et les disposer sur une plaque.',
      'Enfourner pour 12 minutes.',
    ],
    isPublic: true,
  },
];
